### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by SkyLi000** [captcha-challenger/hcaptcha-model-factory#46]
Im having this issue

```markdown
C:\Users\Sky\hcaptcha-model-factory\src>python main.py new
prompt[en] --> sunflower
2022-12-22 21:28:50 | DEBUG - Diagnose task | task_name=sunflower
Use AI to automatically label datasets? {'y', 'n'} --> y
please put all the images in the `unlabel` folder and press any key to continue...
2022-12-22 21:29:02 | INFO - Found 9 images in C:\Users\Sky\hcaptcha-model-factory\data\sunflower\unlabel
2022-12-22 21:29:02 | DEBUG - Extracting embeddings...
C:\Users\Sky\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
2022-12-22 21:29:03 | INFO - Embeddings extracted
2022-12-22 21:29:03 | INFO - PCA..., shape of embs: (9, 512)
2022-12-22 21:29:03 | INFO - PCA done, shape of embs: (9, 9)
2022-12-22 21:29:03 | DEBUG - Clustering...
2022-12-22 21:29:03 | DEBUG - Clustering done
2022-12-22 21:29:03 | INFO - Saving labels...
2022-12-22 21:29:03 | DEBUG - Labels saved
2022-12-22 21:29:03 | SUCCESS - Auto labeling completed
Start automatic training? {'y', 'n'} --> y
2022-12-22 21:29:04 | DEBUG - Diagnose task | task_name=sunflower
2022-12-22 21:29:04 | ERROR - An error has been caught in function 'new', process 'MainProcess' (16996), thread 'MainThread' (4960):
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    Fire(Scaffold)
  File "C:\Users\Sky\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\Sky\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\Sky\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "C:\Users\Sky\hcaptcha-model-factory\src\apis\scaffold.py", line 78, in new
    Scaffold.train(task=task)
  File "C:\Users\Sky\hcaptcha-model-factory\src\apis\scaffold.py", line 98, in train
    model = Scaffold._model or ResNet(
  File "C:\Users\Sky\hcaptcha-model-factory\src\factories\kernel.py", line 93, in __init__
    self._build_env()
  File "C:\Users\Sky\hcaptcha-model-factory\src\factories\resnet.py", line 64, in _build_env
    raise FileNotFoundError(
FileNotFoundError: The structure of the dataset is incomplete | dir=C:\Users\Sky\hcaptcha-model-factory\data\sunflower
```

im using python 3.8.1

torchvision==0.9.2
torch==1.8.2

those 2 has to be changed cus it it couldnt find the avaliable version

torchvision==0.10.0
torch==1.9.0

that is what i changed it to

**Comment by QIN2DIM** [comment]
You need to manually program the **yes** and **bad** folders and then run the task with the `trainval` command.
