### ISSUE TITLE
[question] Need help training my models

### ISSUE THREAD

**Issue by diegoooooooooooooooo** [captcha-challenger/hcaptcha-model-factory#58]
I tried to train my models with a version of python 3.8, I organized my images well because the ia function does not work correctly for me.
here is a screenshot
![image](https://github.com/captcha-challenger/hcaptcha-model-factory/assets/38768160/54850288-e7ac-4a76-892d-c302375bea4f)
I also tried the python command main.py train suitcase
it gives me a result then causes an error here is the output

`F:\documents\hcaptcha-model-factory-main\src>python main.py train suitcase
2023-08-30 17:06:52 | DEBUG - Diagnose task | task_name=suitcase
2023-08-30 17:06:53 | INFO - >> TRAIN [ResNetMini] - total_params=75154 model=ResNetMini(
  (conv1): Conv2d(3, 16, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (resblock1): ResidualBlock(
    (conv1): Conv2d(16, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (conv2): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn2): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (downsample): Sequential(
      (0): Conv2d(16, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (resblock2): ResidualBlock(
    (conv1): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (downsample): Sequential(
      (0): Conv2d(32, 64, kernel_size=(1, 1), stride=(2, 2), bias=False)
      (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (avgpool): AvgPool2d(kernel_size=7, stride=1, padding=0)
  (fc): Linear(in_features=256, out_features=2, bias=True)
)
2023-08-30 17:06:53 | INFO - Dataset loaded 837 images from F:\documents\hcaptcha-model-factory-main\data\suitcase\train.yaml
C:\Users\Fabien\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
2023-08-30 17:06:55 | ERROR - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (56164), thread 'MainThread' (47704):
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    Fire(Scaffold)
  File "C:\Users\Fabien\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\Fabien\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
> File "C:\Users\Fabien\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "F:\documents\hcaptcha-model-factory-main\src\apis\scaffold.py", line 105, in train
    model.train()
  File "F:\documents\hcaptcha-model-factory-main\src\factories\resnet.py", line 322, in train
    self._train(
  File "F:\documents\hcaptcha-model-factory-main\src\factories\resnet.py", line 188, in _train
    for i, (img, label, _) in enumerate(data_loader):
  File "C:\Users\Fabien\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\Fabien\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\Fabien\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Fabien\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\documents\hcaptcha-model-factory-main\src\components\dataset\binary.py", line 70, in __getitem__
    img = Image.open(fname).convert("RGB")
  File "C:\Users\Fabien\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\PIL\Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'F:\\documents\\hcaptcha-model-factory-main\\data\\suitcase\\bad\\d41d8cd98f00b204e9800998ecf8427e.png'`

I also tried the python command main.py trainval suitcase it gives me a result then causes an error as follows

`F:\documents\hcaptcha-model-factory-main\src>python main.py trainval suitcase
2023-08-30 17:10:24 | DEBUG - Diagnose task | task_name=suitcase
2023-08-30 17:10:24 | INFO - >> TRAIN [ResNetMini] - total_params=75154 model=ResNetMini(
  (conv1): Conv2d(3, 16, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (resblock1): ResidualBlock(
    (conv1): Conv2d(16, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (conv2): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn2): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (downsample): Sequential(
      (0): Conv2d(16, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (resblock2): ResidualBlock(
    (conv1): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (downsample): Sequential(
      (0): Conv2d(32, 64, kernel_size=(1, 1), stride=(2, 2), bias=False)
      (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (avgpool): AvgPool2d(kernel_size=7, stride=1, padding=0)
  (fc): Linear(in_features=256, out_features=2, bias=True)
)
2023-08-30 17:10:24 | INFO - Dataset loaded 837 images from F:\documents\hcaptcha-model-factory-main\data\suitcase\train.yaml
C:\Users\Fabien\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
2023-08-30 17:10:26 | ERROR - An error has been caught in function 'trainval', process 'MainProcess' (56136), thread 'MainThread' (27116):
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    Fire(Scaffold)
  File "C:\Users\Fabien\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\Fabien\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\Fabien\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "F:\documents\hcaptcha-model-factory-main\src\apis\scaffold.py", line 161, in trainval
    Scaffold.train(task, epochs, batch_size)
  File "F:\documents\hcaptcha-model-factory-main\src\apis\scaffold.py", line 105, in train
    model.train()
  File "F:\documents\hcaptcha-model-factory-main\src\factories\resnet.py", line 322, in train
    self._train(
  File "F:\documents\hcaptcha-model-factory-main\src\factories\resnet.py", line 188, in _train
    for i, (img, label, _) in enumerate(data_loader):
  File "C:\Users\Fabien\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\Fabien\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\Fabien\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Fabien\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\documents\hcaptcha-model-factory-main\src\components\dataset\binary.py", line 70, in __getitem__
    img = Image.open(fname).convert("RGB")
  File "C:\Users\Fabien\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\PIL\Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'F:\\documents\\hcaptcha-model-factory-main\\data\\suitcase\\bad\\d41d8cd98f00b204e9800998ecf8427e.png'
2023-08-30 17:10:26 | DEBUG - Diagnose task | task_name=suitcase
2023-08-30 17:10:27 | ERROR - ModelNotFound | path=F:\documents\hcaptcha-model-factory-main\model\suitcase\suitcase.pth`

how to fix this so that i can get there thank you in advance

**Comment by diegoooooooooooooooo** [comment]
I found why it gave me errors
in fact it seemed that the images were not good so it caused an unmanageable error, so I modified the code so that if it came across a bad image it would delete it and move on to the next one
here is the correct complete code of cluster.py

`
import os
import shutil
from glob import glob
from typing import List

import numpy as np
from PIL import Image
from loguru import logger
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

from components.utils import ToolBox
from .base import BaseLabeler
from .img2emb import Img2Emb

###########################################
#add class
from PIL import UnidentifiedImageError
###########################################


class ClusterLabeler(BaseLabeler):
    def __init__(
        self,
        data_dir,
        num_class: int = 2,
        labels: List[str] = None,
        num_feat: int = 128,
        model: str = "resnet-18",
        layer: str = "default",
        layer_output_size: int = 512,
        save: bool = False,
    ) -> None:
        super().__init__(data_dir, num_class, labels)
        self.img2emb = Img2Emb(
            model=model, layer=layer, layer_output_size=layer_output_size, save=save
        )
        self.num_feat = num_feat
        self._dir_unlabel = os.path.join(self.data_dir, "unlabel")

        if not os.path.exists(self._dir_unlabel):
            raise ValueError(
                f"Unlabelled directory not found: {self._dir_unlabel}, please run `scaffold new` first"
            )

        self.images = []
        self.embs = []

    def run(self):
        self.images = []
        for ext in ToolBox.IMAGE_EXT:
            self.images.extend(glob(os.path.join(self._dir_unlabel, f"**/*.{ext}"), recursive=True))
        self.images = sorted(self.images)

        if len(self.images) == 0:
            raise ValueError(f"No images found in {self._dir_unlabel}")

        logger.info(f"Found {len(self.images)} images in {self._dir_unlabel}")
        logger.debug("Extracting embeddings...")
        for i, img_path in enumerate(self.images):
            try:
                img = Image.open(img_path)
                emb = self.img2emb.get_emb(img)
                self.embs.append(emb)
            except UnidentifiedImageError:
                logger.error(f"Cannot identify image file {img_path}, deleting it.")
                os.remove(img_path)
                continue  # Skip the current iteration and move to the next image

            if (i + 1) % 100 == 0:
                logger.info(f"Extracted {(i + 1)} embeddings")
        logger.info("Embeddings extracted")

        self.embs = np.array(self.embs)
        logger.info(f"PCA..., shape of embs: {self.embs.shape}")
        self.embs = PCA(n_components=min(self.num_feat, self.embs.shape[0])).fit_transform(self.embs)
        logger.info(f"PCA done, shape of embs: {self.embs.shape}")

        logger.debug("Clustering...")
        kmeans = KMeans(n_clusters=self.num_class).fit(self.embs)
        logger.debug("Clustering done")
        labels_ = np.array(kmeans.labels_)  # noqa
        logger.info("Saving labels...")
        for i, label in enumerate(labels_):
            label = self.labels[label]
            img = self.images[i]
            img_name = os.path.basename(img)
            label_path = os.path.join(self.data_dir, label)
            if not os.path.exists(label_path):
                os.makedirs(label_path)
            shutil.copy(img, os.path.join(label_path, img_name))
        logger.debug("Labels saved")

`
